zuul:
  sensitiveHeaders: usuario, clave
  routes:
    google:
      path: /google/**
      url: https://www.google.com/
    gaes:
      path: /gaes/**
      url: http://gaes-credito-consumo-dev.apps.sv-bsnc-arquitectura-openshift.itac.com.co/
    privado:
      path: /privado/**
      url: http://www.profesor-p.com
    local:
      path: /local/**
      url: http://localhost:8080/api      
    url:
      path: /url/**
      url: http://url.com
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000