kind: Template
apiVersion: v1
metadata:
  name: angular-web-app-front-gaes-itac
  annotations:
    iconClass: icon-jboss
    tags: nodejs, angular, web app
    openshift.io/display-name: Frontend GAES
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    description: Just building a little angular app with a web builder
parameters:
  - displayName: Application Name
    description: The name for the application.
    name: APPLICATION_NAME
    value: tfc-frontend
    required: true
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: master
    required: true
  - name: SOURCE_REPOSITORY_DIR
    description: The location within the source repo of the application
    displayName: Source Directory
    value: .
    required: true
  - name: OUTPUT_DIR
    description: The location of the compiled static files from your web apps builder
    displayName: Output Directory
    value: build
    required: false
  - name: NPM_BUILD
    description: Allows customizing the default npm run build command
    displayName: NPM Build command
    value: npm run build
    required: false
  - name: HTTP_PROXY
    description: http proxy
    displayName: http proxy
    value:
    required: false
  - name: HTTPS_PROXY
    description: https proxy
    displayName: https proxy
    value:
    required: false
  - name: NO_PROXY
    description: no proxy for
    displayName: no proxy for
    value:
    required: false
  - name: GITHUB_WEBHOOK_SECRET
    description: A secret string used to configure the GitHub webhook.
    displayName: GitHub Webhook Secret
    required: true
    from: '[a-zA-Z0-9]{40}'
    generate: expression
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: angular-web-app-front-gaes-itac-builder
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: angular-web-app-front-gaes-itac-runtime
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: web-app-builder-runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: nodeshift/centos7-s2i-web-app:latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: angular-web-app-front-gaes-itac-builder
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: angular-web-app-front-gaes-itac-builder:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      sourceSecret:
        name: "git-secret"
      contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: GIT_SSL_NO_VERIFY
            value: 'true'
          - name: OUTPUT_DIR
            value: ${OUTPUT_DIR}
          - name: NPM_BUILD
            value: ${NPM_BUILD}
          - name: HTTP_PROXY
            value: ${HTTP_PROXY}
          - name: HTTPS_PROXY
            value: ${HTTPS_PROXY}
          - name: NO_PROXY
            value: ${NO_PROXY}
        from:
          kind: ImageStreamTag
          name: web-app-builder-runtime:latest
        incremental: true
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: angular-web-app-front-gaes-itac-runtime
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: angular-web-app-front-gaes-itac-runtime:latest
    postCommit: {}
    resources: {}
    source:
      type: Image
      images:
        - from:
            kind: ImageStreamTag
            name: angular-web-app-front-gaes-itac-builder:latest
          paths:
            - destinationDir: .
              sourcePath: /opt/app-root/output/.
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nginx-image-runtime:latest
        incremental: true
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: angular-web-app-front-gaes-itac-builder:latest
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: "${APPLICATION_NAME}"
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: angular-web-app-front-gaes-itac-runtime
          imagePullPolicy: IfNotPresent
          name: angular-web-app-front-gaes-itac-runtime
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          envFrom:
          - configMapRef:
              name: ${APPLICATION_NAME}
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - angular-web-app-front-gaes-itac-runtime
          from:
            kind: ImageStreamTag
            name: 'angular-web-app-front-gaes-itac-runtime:latest'
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      app: "${APPLICATION_NAME}"
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
