# config de endpoint info para spring actuator
info:
  app:
    name: ${project.name}
    description: Servicio acceso datos calculadora
    version: ${project.version}
# config de endpoints para spring actuator
endpoints:
  enabled: false
  health:
    enabled: true
logging:
  config: classpath:logback.xml
# config de endpoints para spring actuator
management:
  server:
    address: 0.0.0.0
    port: 8080
  endpoint:
    restart:
      enabled: true
server:
  address: 0.0.0.0
  port: 8080
spring:
  cloud:
    kubernetes:
      # define politica para el servicio cuando se hacen cambios en el configmap
      reload:
        enabled: true
  datasource:
    password: ${DB_PASSWORD}
    platform: postgresql
    username: ${DB_USER}
    url: jdbc:postgresql://${database.host}:${database.port}/${DB_NAME}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${acceso-datos-calculadora.db.schema}
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  flyway:
    url: jdbc:postgresql://${database.host}:${database.port}/${DB_NAME}
    schemas: ${acceso-datos-calculadora.db.schema}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  profiles:
    active: "@spring.profiles.active@"